name: "Validation Firmware"
description: "Compilation d'un sketch Arduino"

runs:
  using: "composite"
  steps:
    - name: Compilation     
      uses: arduino/compile-sketches@v1
      with:
        fqbn: 'arduino:avr:uno'
        sketch-paths: '- firmware'
        verbose: True
