name: Analyse des performances

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtention du code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run a one-line script
        run: echo Hello, world!

    
