name: CPP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtention du code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Installation des dépendances du système
        run: | 
          sudo apt-get update
          sudo apt-get install ninja-build cmake build-essential python3
    
      
      - name: Création du dossier de compilation
        working-directory: library/cppcount
        run: |
          mkdir build

      - name: Compilation
        working-directory: library/cppcount/build
        run: |
          cmake ..
          make
          
      - name: Exécution des tests
        working-directory: library/cppcount/build/cppcount/tests
        run: |
          ./test_cppcount
          
      - name: Compilation du module Python
        working-directory: library/cppcount
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build
          python3 -m build
