# This is a basic workflow to help you get started with Actions
name: Test de compilation du Firmware

on:
  workflow_dispatch:
    branches: [main]
    
  pull_request:
    branches: [dev, main]
    
jobs:
  build:

    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: arduino/compile-sketches@v1
      with:
        fqbn: 'arduino:avr:uno'
        sketch-paths: '- firmware'
