name: Test de compilation du Firmware

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Compilation du firmware Arduino
      uses: ./.github/actions/action-firmware-test
